import { SlidingWindowLimiter, sleep } from "@/lib/rate-limiter";

// Model ID checked live against ai.google.dev/pricing (2026-07-27) rather than
// trusted from memory — docs/00_README.md explicitly warns free-tier model
// names shift over time. Re-check there if this ever starts 404ing.
const MODEL = "gemini-3.6-flash";

// The free tier caps requests per minute, tokens per minute AND requests per
// day, and blowing any one of them returns 429 (ai.google.dev/gemini-api/docs/
// rate-limits). The daily quota resets at midnight Pacific.
//
// The per-day cap is why summaries are generated by one scheduled batch instead
// of on page view: a batch costs a fixed roster-size + 1 calls a day, whereas
// regenerating on view scaled with how much anyone happened to browse.
//
// This limiter guards the per-minute side within a single batch.
//
// Being *too* conservative here is not free, which is easy to get wrong: the
// batch runs inside a serverless function capped at 60s, so pacing that can't
// fit a roster-sized run in that window means the job is permanently partial
// and never catches up. At 4s spacing a 6-summary batch spends ~20s waiting,
// which leaves room for the generations themselves.
//
// The exact free-tier RPM isn't published as a stable number, so this is a
// balance rather than a derived value — the 429 backoff below is the real
// safety net, and Google's own guidance is to lean on retries rather than
// trying to predict the limit.
const GEMINI_LIMIT_WINDOWS = [{ limit: 15, intervalMs: 60_000 }];

export const geminiLimiter = new SlidingWindowLimiter(GEMINI_LIMIT_WINDOWS);

// Retry with exponential backoff, per Google's guidance. Kept short on purpose:
// this runs inside a time-budgeted batch, so a single unlucky call must not be
// able to eat the whole run. Worst case here is 2+4+8 = 14s.
const MAX_RETRIES = 3;
const BASE_BACKOFF_MS = 2_000;

// Longest wait worth sitting through inside a time-budgeted batch. Past this,
// give up cleanly and let the run finish partial rather than being killed
// mid-write by the function timeout.
const MAX_HONOURED_BACKOFF_MS = 20_000;

export class GeminiApiError extends Error {
  status: number;
  /** Google's quotaId for the limit that was hit, when it says. */
  quotaId?: string;
  /** Seconds Google asked us to wait, from RetryInfo. */
  retryAfterSeconds?: number;

  constructor(
    status: number,
    message: string,
    extra?: { quotaId?: string; retryAfterSeconds?: number },
  ) {
    super(message);
    this.status = status;
    this.quotaId = extra?.quotaId;
    this.retryAfterSeconds = extra?.retryAfterSeconds;
  }
}

// A 429 body follows Google's standard error model: error.details carries a
// QuotaFailure naming which limit was hit and a RetryInfo saying how long to
// wait. Neither is contractually guaranteed for this API, so everything here is
// best-effort — a shape we don't recognise just yields undefined and the caller
// falls back to plain exponential backoff.
//
// Reading this matters because 429 covers two completely different situations:
// the per-minute limit (wait under a minute) and the per-day one (wait until
// midnight Pacific). Guessing which sends you to the wrong place.
type GoogleErrorDetail = {
  "@type"?: string;
  retryDelay?: string;
  violations?: { quotaId?: string; quotaMetric?: string }[];
};

function parseErrorBody(body: string): { quotaId?: string; retryAfterSeconds?: number } {
  try {
    const parsed = JSON.parse(body) as { error?: { details?: GoogleErrorDetail[] } };
    const details = parsed.error?.details ?? [];

    const retryDelay = details.find((d) => d.retryDelay)?.retryDelay;
    // Formatted as a protobuf Duration, e.g. "27s" or "1.5s".
    const seconds = retryDelay ? Number.parseFloat(retryDelay.replace(/s$/, "")) : NaN;

    const quotaId = details.flatMap((d) => d.violations ?? []).find((v) => v.quotaId)?.quotaId;

    return {
      quotaId,
      retryAfterSeconds: Number.isFinite(seconds) ? seconds : undefined,
    };
  } catch {
    return {};
  }
}

// Google's quotaIds spell out the window, e.g.
// "GenerateRequestsPerMinutePerProjectPerModel-FreeTier" vs ...PerDay...
function quotaWindow(quotaId: string | undefined): "minute" | "day" | null {
  if (!quotaId) return null;
  if (/PerMinute/i.test(quotaId)) return "minute";
  if (/PerDay/i.test(quotaId)) return "day";
  return null;
}

// True for the errors worth waiting out: rate limiting and transient capacity
// problems. A 400 (bad prompt) or 403 (bad key) will never succeed on retry.
//
// 503 in particular is Gemini saying the model is overloaded right now — it has
// nothing to do with the key, the quota or the prompt, and it usually clears in
// seconds. Worth surfacing differently from 429 wherever this reaches a person.
function isRetryable(status: number): boolean {
  return status === 429 || status === 500 || status === 503;
}

// One place that turns a Gemini failure into something a person can act on.
// "Rejected" is the wrong word for most of these and sends you looking in the
// wrong place — an overloaded model reads as a broken API key otherwise.
export function describeGeminiError(e: unknown): string {
  if (!(e instanceof GeminiApiError)) {
    return e instanceof Error ? e.message : "Failed to generate summaries.";
  }

  switch (e.status) {
    case 429: {
      // 429 covers both the per-minute and the per-day cap, and the difference
      // is "wait a minute" vs "wait until tomorrow". Only say which when
      // Google's own quotaId says so — asserting the daily one on a per-minute
      // burst is how you end up thinking the feature is broken.
      const wait = e.retryAfterSeconds
        ? ` Google asked for ${Math.ceil(e.retryAfterSeconds)}s.`
        : "";

      switch (quotaWindow(e.quotaId)) {
        case "minute":
          return `Hit Gemini's per-minute rate limit.${wait || " Wait a minute and run it again."}`;
        case "day":
          return "Hit Gemini's per-day free-tier quota — it resets at midnight Pacific.";
        default:
          return `Hit a Gemini rate limit (429).${wait} If running it again in a minute doesn't help, it's the daily free-tier quota, which resets at midnight Pacific.`;
      }
    }
    case 500:
    case 503:
      return "Gemini's model is overloaded right now (503). Nothing's wrong with the key or the quota — try again in a minute.";
    case 400:
      return "Gemini rejected the prompt (400). Usually means the clan context grew past what the model will accept.";
    case 401:
    case 403:
      return "Gemini refused the API key (check GEMINI_API_KEY).";
    default:
      return `Gemini call failed (${e.status}).`;
  }
}

export async function generateText(prompt: string, apiKey: string): Promise<string> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${apiKey}`;

  for (let attempt = 0; ; attempt += 1) {
    await geminiLimiter.acquire();

    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }),
    });

    if (!res.ok) {
      const body = await res.text();
      const { quotaId, retryAfterSeconds } = parseErrorBody(body);

      // A per-day quota cannot recover within this run, and every retry is
      // itself a request counted against it — retrying here would spend four
      // requests to learn what the first one already said. Give up at once.
      if (quotaWindow(quotaId) === "day") {
        throw new GeminiApiError(res.status, `Gemini API request failed (${res.status}): ${body}`, {
          quotaId,
          retryAfterSeconds,
        });
      }

      if (isRetryable(res.status) && attempt < MAX_RETRIES) {
        // Prefer Google's own RetryInfo over guessing — it knows when the
        // window actually reopens. Blind exponential backoff tops out at 14s,
        // which is shorter than a 60s per-minute window, so without this a
        // per-minute 429 survives every retry and surfaces as a hard failure.
        const requested = retryAfterSeconds ? retryAfterSeconds * 1_000 : 0;
        const backoff = Math.max(requested, BASE_BACKOFF_MS * 2 ** attempt);

        // No point waiting out a per-day quota, and a long wait would blow the
        // batch's time budget anyway. Fail now; the run ends partial and the
        // stale flags survive for the next one.
        if (backoff > MAX_HONOURED_BACKOFF_MS) {
          throw new GeminiApiError(res.status, `Gemini API request failed (${res.status}): ${body}`, {
            quotaId,
            retryAfterSeconds,
          });
        }

        // Park the shared limiter too, not just this call — during a batch the
        // next summary would otherwise walk straight into the same wall.
        geminiLimiter.notifyRateLimited(backoff);
        await sleep(backoff);
        continue;
      }

      throw new GeminiApiError(res.status, `Gemini API request failed (${res.status}): ${body}`, {
        quotaId,
        retryAfterSeconds,
      });
    }

    const data = (await res.json()) as {
      candidates?: { content?: { parts?: { text?: string }[] } }[];
    };

    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
      throw new GeminiApiError(502, "Gemini returned no summary text.");
    }
    return text.trim();
  }
}
