-- Tournament schema and seed data for the LEIF 8 operations dashboard
-- This file creates the complete Supabase/PostgreSQL schema for:
--  * tournament_dates
--  * tournament_groups
--  * tournament_group_teams
--  * tournament_matches
-- It also includes RLS policies and automatic seed data for the tournament structure.

BEGIN;

-- -------------------------------------------------------------------------
-- Core tables
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tournament_teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  tag TEXT NOT NULL,
  logo_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tournament_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  sequence_order INT NOT NULL UNIQUE,
  scheduled_at TIMESTAMPTZ NOT NULL,
  is_locked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tournament_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_id BIGINT NOT NULL REFERENCES tournament_dates(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(date_id, name)
);

CREATE TABLE IF NOT EXISTS tournament_group_teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES tournament_groups(id) ON DELETE CASCADE,
  team_id BIGINT REFERENCES tournament_teams(id) ON DELETE SET NULL,
  seed INT NOT NULL CHECK (seed BETWEEN 1 AND 4),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(group_id, seed),
  UNIQUE(group_id, team_id)
);

CREATE TABLE IF NOT EXISTS tournament_matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT REFERENCES tournament_groups(id) ON DELETE CASCADE,
  date_id BIGINT NOT NULL REFERENCES tournament_dates(id) ON DELETE CASCADE,
  stage TEXT NOT NULL CHECK (stage IN (
    'Semifinal_1',
    'Semifinal_2',
    'Final',
    'Third_Place',
    'Playoff_Semi_1',
    'Playoff_Semi_2',
    'Playoff_Final'
  )),
  format TEXT NOT NULL CHECK (format IN ('Bo1', 'Bo3', 'Bo5')),
  team_a_id BIGINT REFERENCES tournament_teams(id) ON DELETE SET NULL,
  team_b_id BIGINT REFERENCES tournament_teams(id) ON DELETE SET NULL,
  score_a INT CHECK (score_a >= 0),
  score_b INT CHECK (score_b >= 0),
  status TEXT NOT NULL CHECK (status IN ('Scheduled', 'Live', 'Finished')) DEFAULT 'Scheduled',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(group_id, stage)
);

-- -------------------------------------------------------------------------
-- Automatic timestamp maintenance
-- -------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION tournament_matches_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_tournament_matches_updated_at ON tournament_matches;
CREATE TRIGGER set_tournament_matches_updated_at
BEFORE UPDATE ON tournament_matches
FOR EACH ROW EXECUTE FUNCTION tournament_matches_updated_at();

-- -------------------------------------------------------------------------
-- Indexes
-- -------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_tournament_matches_group_id ON tournament_matches(group_id);
CREATE INDEX IF NOT EXISTS idx_tournament_matches_date_id ON tournament_matches(date_id);
CREATE INDEX IF NOT EXISTS idx_tournament_group_teams_group_id ON tournament_group_teams(group_id);
CREATE INDEX IF NOT EXISTS idx_tournament_groups_date_id ON tournament_groups(date_id);

-- -------------------------------------------------------------------------
-- Row Level Security policies
-- -------------------------------------------------------------------------

ALTER TABLE tournament_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournament_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournament_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournament_group_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournament_matches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tournament public select" ON tournament_teams
  FOR SELECT USING (true);
CREATE POLICY "Tournament authenticated modify" ON tournament_teams
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Fecha public select" ON tournament_dates
  FOR SELECT USING (true);
CREATE POLICY "Fecha authenticated modify" ON tournament_dates
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Group public select" ON tournament_groups
  FOR SELECT USING (true);
CREATE POLICY "Group authenticated modify" ON tournament_groups
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Group team public select" ON tournament_group_teams
  FOR SELECT USING (true);
CREATE POLICY "Group team authenticated modify" ON tournament_group_teams
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Match public select" ON tournament_matches
  FOR SELECT USING (true);
CREATE POLICY "Match authenticated modify" ON tournament_matches
  FOR ALL USING (auth.role() = 'authenticated');

-- -------------------------------------------------------------------------
-- Seed the tournament structure
-- -------------------------------------------------------------------------

INSERT INTO tournament_dates (name, sequence_order, scheduled_at)
VALUES
  ('Fecha 1', 1, '2026-05-16 14:00:00-03'),
  ('Fecha 2', 2, '2026-05-30 14:00:00-03'),
  ('Fecha 3', 3, '2026-06-13 14:00:00-03'),
  ('Playoffs', 4, '2026-06-27 14:00:00-03')
ON CONFLICT (name) DO NOTHING;

INSERT INTO tournament_groups (date_id, name)
SELECT d.id, g.name
FROM tournament_dates d,
LATERAL (VALUES
  ('Group A'),
  ('Group B'),
  ('Group C'),
  ('Group D')
) AS g(name)
WHERE d.sequence_order BETWEEN 1 AND 3
ON CONFLICT (date_id, name) DO NOTHING;

INSERT INTO tournament_groups (date_id, name)
SELECT id, 'Playoffs'
FROM tournament_dates
WHERE sequence_order = 4
ON CONFLICT (date_id, name) DO NOTHING;

INSERT INTO tournament_group_teams (group_id, seed)
SELECT g.id, s.seed
FROM tournament_groups g
CROSS JOIN (VALUES (1), (2), (3), (4)) AS s(seed)
ON CONFLICT (group_id, seed) DO NOTHING;

INSERT INTO tournament_matches (group_id, date_id, stage, format)
SELECT g.id, g.date_id, 'Semifinal_1', 'Bo1'
FROM tournament_groups g
WHERE g.name IN ('Group A', 'Group B', 'Group C', 'Group D')
ON CONFLICT (group_id, stage) DO NOTHING;

INSERT INTO tournament_matches (group_id, date_id, stage, format)
SELECT g.id, g.date_id, 'Semifinal_2', 'Bo1'
FROM tournament_groups g
WHERE g.name IN ('Group A', 'Group B', 'Group C', 'Group D')
ON CONFLICT (group_id, stage) DO NOTHING;

INSERT INTO tournament_matches (group_id, date_id, stage, format)
SELECT g.id, g.date_id, 'Final', 'Bo1'
FROM tournament_groups g
WHERE g.name IN ('Group A', 'Group B', 'Group C', 'Group D')
ON CONFLICT (group_id, stage) DO NOTHING;

INSERT INTO tournament_matches (group_id, date_id, stage, format)
SELECT g.id, g.date_id, 'Third_Place', 'Bo1'
FROM tournament_groups g
WHERE g.name IN ('Group A', 'Group B', 'Group C', 'Group D')
ON CONFLICT (group_id, stage) DO NOTHING;

INSERT INTO tournament_matches (group_id, date_id, stage, format)
SELECT g.id, g.date_id, 'Playoff_Semi_1', 'Bo3'
FROM tournament_groups g
WHERE g.name = 'Playoffs'
ON CONFLICT (group_id, stage) DO NOTHING;

INSERT INTO tournament_matches (group_id, date_id, stage, format)
SELECT g.id, g.date_id, 'Playoff_Semi_2', 'Bo3'
FROM tournament_groups g
WHERE g.name = 'Playoffs'
ON CONFLICT (group_id, stage) DO NOTHING;

INSERT INTO tournament_matches (group_id, date_id, stage, format)
SELECT g.id, g.date_id, 'Playoff_Final', 'Bo5'
FROM tournament_groups g
WHERE g.name = 'Playoffs'
ON CONFLICT (group_id, stage) DO NOTHING;

COMMIT;
